baseURL: 'https://bouncmpe.github.io'
languageCode: en-us

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

enableRobotsTXT: true
enableInlineShortcodes: true
enableGitInfo: true
enableMissingTranslationPlaceholders: true

externalLinks:
  cue: true
  tab: true

pagination: 
  pagerSize: 16
timeout: 300s

cleanDestinationDir: true
