main:
  - name: Hakkında
    url: /about/
    identifier: about
    weight: 100

  - name: Kişiler
    url: /people/
    identifier: people
    weight: 200
  - name: Öğretim Üyeleri
    url: /people/faculty
    parent: people
    identifier: faculty
    weight: 201
  - name: Akademik Personel
    url: /people/academic-staff
    parent: people
    identifier: academic-staff
    weight: 202
  - name: İdari ve Yardımcı Personel
    url: /people/support-staff
    parent: people
    identifier: support-staff
    weight: 203
  # - name: Öğrenciler
  #   url: /people/students
  #   parent: people
  #   identifier: students
  #   weight: 204

  - name: Lisans
    url: /undergraduate/
    identifier: undergraduate
    weight: 300
  - name: Genel Bakış
    url: /undergraduate/overview
    parent: undergraduate
    identifier: undergraduate-overview
    weight: 301
  - name: Öğretim Programı
    url: /undergraduate/curriculum
    parent: undergraduate
    identifier: undergraduate-curriculum
    weight: 302
  # - name: Temel Dersler
  #   url: /undergraduate/courses
  #   parent: undergraduate
  #   identifier: undergraduate-courses
  #   weight: 303
  - name: Seçmeli Dersler
    url: /undergraduate/electives
    parent: undergraduate
    identifier: undergraduate-electives
    weight: 304
  - name: Çift Ana Dal Programları
    url: /undergraduate/double-major
    parent: undergraduate
    identifier: undergraduate-double-major
    weight: 305
  - name: Yan Dal Programları
    url: /undergraduate/minor-degree
    parent: undergraduate
    identifier: undergraduate-minor-degree
    weight: 306
  - name: Değişim Programları
    url: /undergraduate/exchange
    parent: undergraduate
    identifier: undergraduate-exchange
    weight: 307
  - name: Endüstri Stajı
    url: /undergraduate/training
    parent: undergraduate
    identifier: undergraduate-training
    weight: 308
  - name: Bitirme Projeleri
    url: /undergraduate/senior-projects
    parent: undergraduate
    identifier: undergraduate-senior-projects
    weight: 309
  - name: Mezuniyet
    url: /undergraduate/graduation
    parent: undergraduate
    identifier: undergraduate-graduation
    weight: 310


  - name: Lisansüstü
    url: /graduate/
    identifier: graduate
    weight: 400
  - name: Doktora Programı
    url: /graduate/phd-program
    parent: graduate
    identifier: graduate-phd-program
    weight: 411
  - name: Yüksek Lisans Programı
    url: /graduate/ms-program
    parent: graduate
    identifier: graduate-ms-program
    weight: 412
  - name: Diğer İlişkili Programlar
    url: /graduate/affiliated-programs
    parent: graduate
    identifier: graduate-affiliated
    weight: 413

  - name: Dersler
    url: /courses/
    identifier: courses
    weight: 500

  - name: Araştırma
    url: /research/
    identifier: research
    weight: 600

  # - name: Düzenlemeler
  #   url: /docs/
  #   identifier: docs
  #   weight: 700
