name: 📅 Bilingual Event Submission
description: Submit an event for the website. Provide both English and Turkish entries. Image optional.
title: "[EVENT] <Insert event title>"
labels: ["event"]
body:
  - type: input
    id: title_en
    attributes:
      label: "Event Title (EN)"
      placeholder: "Conditional Computation Techniques in DNNs"
    validations:
      required: true

  - type: input
    id: title_tr
    attributes:
      label: "Event Title (TR)"
      placeholder: "Koşullu Bilgi Kazanım ile Derin Sinir Ağları"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: "Speaker/Presenter Name"
      placeholder: "Ufuk Can Biçici"
    validations:
      required: true

  - type: input
    id: datetime
    attributes:
      label: "Date and Time (ISO format)"
      placeholder: "2025-08-01T14:00:00"
    validations:
      required: true

  - type: input
    id: duration
    attributes:
      label: "Duration"
      placeholder: "2h"
    validations:
      required: true

  - type: input
    id: location_en
    attributes:
      label: "Location (EN)"
      placeholder: "AVŞ Hall"
    validations:
      required: true

  - type: input
    id: location_tr
    attributes:
      label: "Location (TR)"
      placeholder: "Ali Vahit Şahiner Salonu"
    validations:
      required: true

  - type: textarea
    id: image_markdown
    attributes:
      label: "Image (optional, drag & drop)"
      description: "Drag & drop an image to include a poster/cover."
      placeholder: "![alt text](https://user-images.githubusercontent.com/.../your-image.png)"

  - type: textarea
    id: description_en
    attributes:
      label: "Description (EN)"
      placeholder: "This thesis defense will cover conditional computation techniques."
    validations:
      required: true

  - type: textarea
    id: description_tr
    attributes:
      label: "Description (TR)"
      placeholder: "Bu savunmada koşullu hesaplama teknikleri ele alınacaktır."
    validations:
      required: true
