name: Bilingual Event Submission
description: Submit an event for the website. Provide both English and Turkish entries.
title: "[EVENT] <Insert event title>"
labels: ["event"]
body:
  - type: dropdown
    id: event_type
    attributes:
      label: "Event Type"
      options:
        - phd-thesis-defense
        - ms-thesis-defense
        - seminar
        - special-event
      description: "Choose the type of the event"
    validations:
      required: true

  - type: input
    id: title_en
    attributes:
      label: "Event Title (EN)"
      placeholder: "Enter event title here"
    validations:
      required: true

  - type: input
    id: title_tr
    attributes:
      label: "Event Title (TR)"
      placeholder: "Enter event title here"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: "Speaker/Presenter Name"
      placeholder: "Enter presenter name here"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: "Date (YYYY-MM-DD)"
      placeholder: "YYYY-MM-DD"
    validations:
      required: true

  - type: dropdown
    id: time
    attributes:
      label: "Time"
      description: "Choose a time slot"
      options:
        - "09:00"
        - "09:30"
        - "10:00"
        # …etc…
    validations:
      required: true

  - type: dropdown
    id: duration
    attributes:
      label: "Duration"
      options:
        - 1h
        - 1.5h
        - 2h
        - Other
    validations:
      required: true

  - type: input
    id: location_en
    attributes:
      label: "Location (EN)"
      placeholder: "Enter location here"
    validations:
      required: true

  - type: input
    id: location_tr
    attributes:
      label: "Location (TR)"
      placeholder: "Enter location here"
    validations:
      required: true
