name: Submit Event
description: Submit an event to be published on the CMPE website.
labels: [event, automation]
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Short title for the event
      placeholder: e.g. Graduation Ceremony 2025
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Event Name
      description: The formal name of the event
      placeholder: e.g. Software Engineering
    validations:
      required: true

  - type: input
    id: datetime
    attributes:
      label: Start Date and Time
      description: Use format YYYY-MM-DDTHH:MM:SS
      placeholder: e.g. 2025-07-04T19:00:00
    validations:
      required: true

  - type: input
    id: duration
    attributes:
      label: Duration
      description: Duration in hours (e.g. 2h)
      placeholder: e.g. 2h
    validations:
      required: false

  - type: input
    id: location
    attributes:
      label: Location
      description: Where will the event take place?
      placeholder: e.g. Albert Long Hall
    validations:
      required: true

  - type: textarea
    id: image
    attributes:
      label: Poster or Cover Image
      description: Upload or paste the image URL. Drag-and-drop works in GitHub.
      placeholder: ![poster](https://user-images.githubusercontent.com/your-image.png)
    validations:
      required: false

  - type: textarea
    id: content
    attributes:
      label: Description (EN)
      description: Detailed English description of the event
      placeholder: You may use Markdown.
    validations:
      required: false
