name:  Event Submission
description: Submit an event (seminar, thesis defense, etc.) for the department website
title: "[EVENT] <Insert event title>"
labels: ["event"]
body:
  - type: input
    id: title
    attributes:
      label: "Event Title (TR or EN)"
      description: "Title of the event"
      placeholder: "Conditional Computation Techniques in DNNs"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: "Speaker/Presenter Name"
      description: "Full name of the speaker or student"
      placeholder: "Ufuk Can Biçici"
    validations:
      required: true

  - type: input
    id: datetime
    attributes:
      label: "Date and Time (ISO format)"
      description: "Format like 2024-06-05T13:30:00"
      placeholder: "2024-06-05T13:30:00"
    validations:
      required: true

  - type: input
    id: duration
    attributes:
      label: "Duration"
      placeholder: "2h"

  - type: input
    id: location
    attributes:
      label: "Location"
      placeholder: "Ali Vahit Şahiner (AVŞ)"

  - type: textarea
    id: content
    attributes:
      label: "Extra Information or Abstract (optional)"
      description: "You can write extra context or content"
      placeholder: "Abstract, language, topic, etc."


