name:  Bilingual News Submission
description: Submit a news item for the website. Provide both English and Turkish entries.
title: "[NEWS] <Insert news title>"
labels: ["news"]
body:
  - type: input
    id: title_en
    attributes:
      label: "News Title (EN)"
      placeholder: "Lale Akarun received the Excellence in Research Award"
    validations:
      required: true

  - type: input
    id: title_tr
    attributes:
      label: "News Title (TR)"
      placeholder: "Lale Akarun'a Araştırmada Üstün Başarı Ödülü"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: "Date (YYYY-MM-DD)"
      placeholder: "2024-07-19"
    validations:
      required: true

  - type: input
    id: thumbnail
    attributes:
      label: "Image path (optional)"
      placeholder: "uploads/example.png"

  - type: textarea
    id: description_en
    attributes:
      label: "Short Description (EN)"
      placeholder: "Boğaziçi University Foundation awarded scientists..."
    validations:
      required: true

  - type: textarea
    id: description_tr
    attributes:
      label: "Short Description (TR)"
      placeholder: "Boğaziçi Üniversitesi Vakfı bilim insanlarını ödüllendirdi..."
    validations:
      required: true

  - type: textarea
    id: content_en
    attributes:
      label: "Full Content (EN)"
      description: "Detailed news content in English"
      placeholder: "Boğaziçi University Foundation (BÜVAK) every year..."
    validations:
      required: true

  - type: textarea
    id: content_tr
    attributes:
      label: "Full Content (TR)"
      description: "Detaylı haber içeriği Türkçe"
      placeholder: "Boğaziçi Üniversitesi Vakfı (BÜVAK) her yıl..."
    validations:
      required: true
