name: News Submission
description: Submit a news item to appear on the department website
title: "[NEWS] <insert title here>"
labels: ["news"]
body:
  - type: input
    id: title
    attributes:
      label: Title (TR or EN)
      description: Enter the title of the news item
      placeholder: e.g., Lale Akarun'a Araştırmada Üstün Başarı Ödülü
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date (YYYY-MM-DD)
      placeholder: 2024-07-19
    validations:
      required: true

  - type: input
    id: thumbnail
    attributes:
      label: Image file path (optional)
      placeholder: uploads/example.png

  - type: textarea
    id: description
    attributes:
      label: Short description
      description: Used in the frontmatter
      placeholder: e.g., Boğaziçi Üniversitesi Vakfı ödülü verdi.
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Full Content (TR or EN)
      description: Markdown is supported
      placeholder: >
        Boğaziçi Üniversitesi her yıl araştırmada üstün başarı gösteren bilim insanlarını ödüllendiriyor...
    validations:
      required: true
