name: Close Linked Issues When PR is Closed

on:
  pull_request:
    types: [closed]

permissions:
  issues: write
  pull-requests: read

jobs:
  close-linked-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close linked issues
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const linkedIssues = pr.data.body.match(/(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)/gi);

            if (!linkedIssues) {
              console.log("No linked issues found in PR body.");
              return;
            }

            for (const match of linkedIssues) {
              const issueNumber = parseInt(match.match(/\d+/)[0], 10);
              console.log(`Closing issue #${issueNumber}`);
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                state: "closed",
              });
            }
